### ISSUE TITLE
Author details

### ISSUE THREAD

**Issue by JamesS-D** [JBourton/progblack-formative-groupwork#11]
Should be all pre-emptively write out a section on our pages for our author details to be written within? I've put one at the bottom of my page under a basic heading for the moment, but can change this if needed. Then, we can just write author details for other people if we find them blank. Can just put full name, Durham uni, link to github account for now probably and should be good.

**Comment by JBourton** [comment]
Yeah I think this will be fine for author details, we shouldn't need anything more. Will mark this issue as resolved.
